server:
  port: ${SERVER_POST:8085}

spring:
  config:
    import: optional:consul:127.0.0.1:8500
  application:
    name: simpleAuth0
  cloud:
    consul:
      scheme: http
      host: ${CONSUL_SERVER_HOST:127.0.0.1}
      port: ${CONSUL_SERVER_PORT:8500}
      discovery:
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}
        health-check-path: /actuator/health
        prefer-agent-address: true
        hostname: ${spring.application.name}
        catalog-services-watch-timeout: 5
        health-check-timeout: 15s
        deregister: true
        heartbeat:
          enabled: true
        health-check-critical-timeout: 10s
      config:
        enabled: true
        format: YAML
        name: app
        data-key: config
        profileSeparator: "::"
        prefixes: simpleAuth0
        watch:
          enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_SERVER_HOST:localhost}:${MYSQL_SERVER_PORT:3306}/simpleAuth0?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${MYSQL_SERVER_USERNAME:root}
    password: ${MYSQL_SERVER_PASSWORD:123456}
  flyway:
    baseline-on-migrate: true
    baseline-description: <<Flyway Baseline>>
    enabled: ${FLYWAY_ENABLED:false}
    locations: classpath:db/migration
    validate-on-migrate: true
    fail-on-missing-locations: true
  redis:
    host: ${REDIS_SERVER_HOST:localhost}
    port: ${REDIS_SERVER_PORT:6379}
    password: ${REDIS_SERVER_PASSWORD:123456}
  session:
    store-type: redis
    redis:
      namespace: ${REDIS_SESSION_NAMESPACE:simpleAuth0:session}
      flush-mode: on_save

logging:
  level:
    com.dbappsecurity.iot.iam: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
